services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: lysero
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "532:5432"